
server:
  port: 8080

spring:
  application:
      name: cognito-sb-demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <issuer-uri>

aws:
  accessKeyId: <accessKeyId>
  secretAccessKey: <secretAccessKey>
  region: sa-east-1
  clientId: <clientId>
  clientSecret: <clientSecret>
