
server:
  port: 8080

spring:
  application:
      name: cognito-sb-demo
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - openid
              - phone
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
            redirect-uri: https://localhost:8080/v1/user
        provider:
          cognito:
            issuerUri: issuer-uri
            user-name-attribute: username